UserInterface/Controllers/RequestController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using UserInterface.RequestDetailService;
using UserInterface.Models;
using UserInterface.PurchaseOrderService;
using UserInterface.FinalPurchaseDisplayService;


namespace UserInterface.Controllers
{
    public class RequestController : Controller
    {
        RequestDetailsRetrievalClient retrieve = new RequestDetailsRetrievalClient();
        DisplayFinalPurchaseClient displayClient = new DisplayFinalPurchaseClient();

        public ActionResult RequestDetail(string requestId)
        {
            int intRequestId = Convert.ToInt32(requestId);
            RequestDetail requestDetails = retrieve.getRequestDetail(intRequestId);

            List<UserInterface.RequestDetailService.RequestProductMap> productList = retrieve.getRequestProductsDetails(intRequestId);

            return View(new RequestDetailRetrievalClass(requestDetails, productList));          
        }




        public ActionResult PurchaseOrder(FormCollection collection)
        {
            int intRequestId = Convert.ToInt32(collection["requestDetail.requestId"]);

            RequestDetail requestDetails = retrieve.getRequestDetail(intRequestId);


            string productID = collection["product.productId"];
            int[] productIDArray = productID.Split(',').Select(p => Convert.ToInt32(p)).ToArray();

            string allocation = collection["product.allocatedQuantity"];
            int[] allocationArray = allocation.Split(',').Select(p => Convert.ToInt32(p)).ToArray();

            string required = collection["product.requiredQuantity"];
            int[] requiredArray = required.Split(',').Select(p => Convert.ToInt32(p)).ToArray();

            string available = collection["product.availableQuantity"];
            int[] availableArray = available.Split(',').Select(p => Convert.ToInt32(p)).ToArray();


            PurchaseOrderServiceClient purchaseOrder = new PurchaseOrderServiceClient();

            List<UserInterface.PurchaseOrderService.RequestProductMap> productList = purchaseOrder.getPurchaseProductDetails(productIDArray.ToList(), allocationArray.ToList(), requiredArray.ToList(), intRequestId);
            purchaseOrder.updateProductInventory(productIDArray.ToList(), allocationArray.ToList(), availableArray.ToList());


            if (productList != null)
            {
                var purchaseProductID = productList.Select(i => i.productId).ToArray();

                List<List<ProductVendorMap>> listOfVendorList = purchaseOrder.getVendorProductList(purchaseProductID.ToList(), intRequestId);
                return View(new PurchaseOrderClass(requestDetails, productList, listOfVendorList));
            }

            else
            {
                retrieve.changeRequestStatusToGranted(intRequestId);
                return RedirectToAction("Requests", "Admin");
            }


        }




        public ActionResult DisplayPurchase(FormCollection collection)
        {
            int requestID = Convert.ToInt32(collection["requestDetail.requestId"]);
            RequestDetail requestDetails = retrieve.getRequestDetail(requestID);

            string productID = collection["record.Product.productId"];
            int[] productIDArray = productID.Split(',').Select(p => Convert.ToInt32(p)).ToArray();

            string purchase = collection["record.Product.purchaseQuantity"];
            int[] purchaseArray = purchase.Split(',').Select(p => Convert.ToInt32(p)).ToArray();

            string vendorID = collection["selectedVendorList"];
            int[] vendorIDArray = vendorID.Split(',').Select(p => Convert.ToInt32(p)).ToArray();

            List<SubOrder> subOrderList = displayClient.getSubOrders(requestID, productIDArray.ToList(), purchaseArray.ToList(), vendorIDArray.ToList());

            return View(new PurchaseOrderClass(requestDetails, subOrderList));
        }

        [HttpPost]
        public ActionResult DisplayPurchasePost(FormCollection collection)
        {
            int requestID = Convert.ToInt32(collection["requestDetail.requestId"]);
            retrieve.changeRequestStatusToSent(requestID);

            return RedirectToAction("Requests","Admin");
        }


    }
}

UserInterface/Views/Request/DisplayPurchase.cshtml
@model UserInterface.Models.PurchaseOrderClass

@{
    ViewBag.Title = "DisplayPurchase";
}

<html>
<body>
    <div class="panel-group shadowEffect" style="margin-top:1%;margin-left:5%;margin-right:5%;">
        <div class="panel panel-info">
            <div class="panel-heading"><h4>Purchase Details</h4></div>
            <div class="panel-body">
                <center>
                    <table class="bg-info">
                        <tr><td>Request ID : @Html.DisplayFor(r => r.requestDetail.requestId)</td></tr>
                        <tr><td>Request Date : @Html.DisplayFor(r => r.requestDetail.requestDate)</td></tr>
                        <tr><td>Requester ID : @Html.DisplayFor(r => r.requestDetail.requesterId)</td></tr>
                        <tr><td>Request Priority : @Html.DisplayFor(r => r.requestDetail.requestPriority)</td></tr>
                    </table>
                    <br />


                    @using (Html.BeginForm("DisplayPurchasePost", "Request", FormMethod.Post))
                    {
                        @Html.TextBoxFor(r => r.requestDetail.requestId, new { id = "requestID", type = "hidden" })
                        <table class="bg-info">
                            <tr>
                                <th>Product ID</th>
                                <th>Purchase Quantity</th>
                                <th>Vendor Selected</th>
                                <th>Total Price</th>
                            </tr>

                            @{
                        int sum = 0;
                        foreach (var subOrder in Model.subOrderList)
                        {
                            sum = sum + @subOrder.subOrderTotal;
                            <tr>
                                <td>@subOrder.productID</td>
                                <td>@subOrder.purchaseQuantity</td>
                                <td>@subOrder.vendorID</td>
                                <td>@subOrder.subOrderTotal</td>
                            </tr>
                        }


                        <tr>
                            <td colspan="3">Total</td>
                            <td>@sum</td>
                        </tr>
                            }


                        </table>
                        <br />
                        <button type="submit" class="btn btn-success btn-lg">Send For Approval</button>
                    }
                </center>
                </div>
            </div>
        </div>
</body>
</html>

UserInterface/Views/Request/PurchaseOrder.cshtml
@model UserInterface.Models.PurchaseOrderClass

@{
    ViewBag.Title = "PurchaseOrder";
}

<html>
<body>
    <div class="panel-group shadowEffect" style="margin-top:1%;margin-left:5%;margin-right:5%;">
        <div class="panel panel-info">
            <div class="panel-heading"><h4>Purchase Order Details</h4></div>
            <div class="panel-body">
                <center>
                    <table class="bg-info">
                        <tr><td>Request ID : @Html.DisplayFor(r => r.requestDetail.requestId)</td></tr>
                        <tr><td>Request Date : @Html.DisplayFor(r => r.requestDetail.requestDate)</td></tr>
                        <tr><td>Requester ID : @Html.DisplayFor(r => r.requestDetail.requesterId)</td></tr>
                        <tr><td>Request Priority : @Html.DisplayFor(r => r.requestDetail.requestPriority)</td></tr>
                    </table>
                    <br />


                    @using (Html.BeginForm("DisplayPurchase", "Request", FormMethod.Post))
                    {
                        @Html.TextBoxFor(r => r.requestDetail.requestId, new { id = "requestID", type = "hidden" })
                        <table class="bg-info">
                            <tr>
                                <th>Product ID</th>
                                <th>Product Name</th>
                                <th>Purchase Quantity</th>
                                <th>Select Vendor</th>
                            </tr>

                            @*Code For DropDown*@

                            @{
                        var productVendorList = Model.purchaseProductList.Zip(Model.listOfVendorList, (p, v) => new { Product = p, Vendor = v });

                        foreach (var record in productVendorList)
                        {
                            <tr>
                                <td>@record.Product.productId</td>
                                <td>@record.Product.productName</td>
                                <td>@record.Product.purchaseQuantity</td>

                                @Html.TextBoxFor(m => record.Product.productId, new { type = "hidden" })
                                @Html.TextBoxFor(m => record.Product.productName, new { type = "hidden" })
                                @Html.TextBoxFor(m => record.Product.purchaseQuantity, new { type = "hidden" })

                                @{
                            List<SelectListItem> listItems = new List<SelectListItem>();

                            foreach (var vendor in record.Vendor)
                            {

                                listItems.Add(new SelectListItem
                                {
                                    Value = vendor.vendorID.ToString(),
                                    Text = "Name: " + vendor.vendorName.ToString() + ".......Price: " + vendor.price.ToString(),
                                    Selected = true

                                });
                            }


                                }

                                <td>@Html.DropDownListFor(l => l.selectedVendorList, listItems)</td>

                            </tr>
                        }
                            }

                        </table>
                        <br />
                        <button type="submit" class="btn btn-success btn-lg">View Purchase Order</button>
                    }
                </center>
                </div>
                </div>
        </div>
</body>

</html>

UserInterface/Views/Request/RequestDetail.cshtml
@model UserInterface.Models.RequestDetailRetrievalClass

@{
    ViewBag.Title = "RequestDetail";
}
<html>
<body>
    <div class="panel-group shadowEffect" style="margin-top:1%;margin-left:5%;margin-right:5%;">
        <div class="panel panel-info">
            <div class="panel-heading"><h4>Request Details</h4></div>
            <div class="panel-body">
                <center>
                    <table class="table-striped requestTable">
                        <tr>
                            <td>Request ID</td>
                            <td>@Html.DisplayFor(r => r.requestDetail.requestId)</td>
                        </tr>
                        <tr>
                            <td>Request Date</td>
                            <td>@Html.DisplayFor(r => r.requestDetail.requestDate)</td>
                        </tr>
                        <tr>
                            <td>Requester ID
                            <td>@Html.DisplayFor(r => r.requestDetail.requesterId)</td>
                        </tr>
                        <tr>
                            <td>Request Priority
                            <td>@Html.DisplayFor(r => r.requestDetail.requestPriority)</td>
                        </tr>
                    </table>
                    <br />


                    @using (Html.BeginForm("PurchaseOrder", "Request", FormMethod.Post))
                    {
                        @Html.TextBoxFor(r => r.requestDetail.requestId, new { id = "requestID", type = "hidden" })
                        <table class="table-striped">
                            <tr>
                                <th>Product ID</th>
                                <th>Product Name</th>
                                <th>Required Quantity</th>
                                <th>Available Quantity</th>
                                <th>Allocated Quantity</th>
                            </tr>

                            @foreach (var product in Model.productList)
                            {
                                <tr>
                                    <td>@product.productId</td>
                                    <td>@product.productName</td>
                                    <td>@product.requiredQuantity</td>
                                    <td>@product.availableQuantity</td>

                                    @Html.TextBoxFor(m => product.productId, new { type = "hidden" })
                                    @Html.TextBoxFor(m => product.requiredQuantity, new { type = "hidden" })
                                    @Html.TextBoxFor(m => product.availableQuantity, new { type = "hidden" })

                                    @if (product.requiredQuantity < product.availableQuantity)
                                    {
                                        <td>
                                            @Html.TextBoxFor(m => product.allocatedQuantity, new { type = "number", min = "0", max = @product.requiredQuantity, @class =  "form-control"})

                                        </td>
                                    }

                                    else
                                    {
                                        <td>
                                            @Html.TextBoxFor(m => product.allocatedQuantity, new { type = "number", min = "0", max = product.availableQuantity, @class = "form-control" })

                                        </td>
                                    }

                                </tr>
                            }

                        </table>
                        <br />
                        <button type="submit" class="btn btn-success btn-lg"><span class="glyphicon glyphicon-check"></span> Allocate Available Resources</button>
                    }
                </center>
                </div>
            </div>
        </div>
</body>
</html>